// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ainlafmvlldgkvwdltkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpbmxhZm12bGxkZ2t2d2RsdGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTkzMjMsImV4cCI6MjA2Mjg5NTMyM30.kbyW4ENF7ElU1Jxif5rEZA9pq4rX4ib8UTYuvCTClco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);